runtime: nodejs18 # specify the Node.js version
env: standard

instance_class: F1

automatic_scaling:
  max_instances: 1 # Limits the maximum number of instances
  min_idle_instances: 0 # Minimize idle instances to reduce costs
  min_pending_latency: automatic # Adjust based on your performance requirements
  max_pending_latency: automatic # Adjust based on your performance requirements

env_variables:
  DATABASE_URL: "mysql://root:e378df021f23a6453b298c43a16598182f310820d5741a9320b8060b5f49f7d4@34.128.94.28:3306/edims"
  JWT_SECRET: "yw3FHwo2yAYIG7Fp0UrInRQgc6d9nSiDzG54x80HOgmjg2Hnu3fdmRaKdabYXTD1ylAb8sXgBD6TxkcflXEvSw=="
  PORT: "8080"

network: {}
