runtime: nodejs18 # specify the Node.js version
env: standard

instance_class: F1

automatic_scaling:
  max_instances: 1 # Limits the maximum number of instances
  min_idle_instances: 0 # Minimize idle instances to reduce costs
  min_pending_latency: automatic # Adjust based on your performance requirements
  max_pending_latency: automatic # Adjust based on your performance requirements

env_variables:
  DATABASE_URL: "mysql://gn7uzahkslcltltg7b0h:pscale_pw_oDurpab6YFswSDNjcBMuB2luLoj4mcvVJMtnyhKwS7Y@aws.connect.psdb.cloud/edims?sslaccept=strict"
  JWT_SECRET: "yw3FHwo2yAYIG7Fp0UrInRQgc6d9nSiDzG54x80HOgmjg2Hnu3fdmRaKdabYXTD1ylAb8sXgBD6TxkcflXEvSw=="
  PORT: "8080"

network: {}
