runtime: nodejs14 # specify the Node.js version
env: standard

instance_class: F1

automatic_scaling:
  max_instances: 1 # Limits the maximum number of instances
  min_idle_instances: 0 # Minimize idle instances to reduce costs
  min_pending_latency: automatic # Adjust based on your performance requirements
  max_pending_latency: automatic # Adjust based on your performance requirements

env_variables:
  DATABASE_URL: "mysql://vrqfl7dqdfb9lur6wrkr:pscale_pw_CygtlGxBeiCYt5zE8vi48FKWRMHVEYTwbLNKtG4rxku@aws.connect.psdb.cloud/edims?sslaccept=strict"
  JWT_SECRET: "yw3FHwo2yAYIG7Fp0UrInRQgc6d9nSiDzG54x80HOgmjg2Hnu3fdmRaKdabYXTD1ylAb8sXgBD6TxkcflXEvSw=="
  PORT: "3000"

network: {}
